CREATE TABLE IF NOT EXISTS tag (
  id UUID NOT NULL,
  account_id UUID NOT NULL,
  label CHARACTER VARYING (128) NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  CONSTRAINT tag_pk PRIMARY KEY (id),
  CONSTRAINT tag_1_fk FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS bill_tag (
  bill_id UUID NOT NULL,
  tag_id UUID NOT NULL,
  CONSTRAINT billtag_1_fk FOREIGN KEY (bill_id) REFERENCES bill (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT billtag_2_fk FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE ON UPDATE CASCADE
);
