CREATE TABLE account (
  id UUID NOT NULL,
  name CHARACTER VARYING (256) NOT NULL,
  email CHARACTER VARYING (128) NOT NULL,
  password CHARACTER VARYING (256) NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  CONSTRAINT user_pk PRIMARY KEY (id)
);
