CREATE TABLE IF NOT EXISTS card (
  id UUID NOT NULL,
  account_id UUID NOT NULL,
  label CHARACTER VARYING (128) NOT NULL,
  amount_limit DECIMAL(15, 2) NOT NULL DEFAULT 0,
  close_day INTEGER,
  pay_day INTEGER,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  CONSTRAINT card_pk PRIMARY KEY (id),
  CONSTRAINT card_1_fk FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE CASCADE ON UPDATE CASCADE
);
