CREATE TABLE IF NOT EXISTS category (
  id UUID NOT NULL,
  account_id UUID NOT NULL,
  label CHARACTER VARYING (128) NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  CONSTRAINT category_pk PRIMARY KEY (id),
  CONSTRAINT category_1_fk FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE CASCADE ON UPDATE CASCADE
);
